# Generated by Django 3.0.5 on 2020-05-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
                ('shool', models.CharField(max_length=200)),
                ('stu_id', models.CharField(max_length=200)),
                ('pho_num', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('club_desc', models.TextField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubRecruitment.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
                ('shool', models.CharField(max_length=200)),
                ('stu_id', models.CharField(max_length=200)),
                ('pho_num', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('stu_class', models.CharField(max_length=200)),
                ('mailbox', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_info', models.TextField()),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubRecruitment.Club')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubRecruitment.Student')),
            ],
        ),
    ]
