# Generated by Django 3.0.5 on 2020-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='shool',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shool',
        ),
        migrations.AddField(
            model_name='club',
            name='shool',
            field=models.CharField(default='', max_length=200),
        ),
    ]
