# Generated by Django 3.0.5 on 2020-05-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubRecruitment.Department'),
            preserve_default=False,
        ),
    ]
