# Generated by Django 3.0.5 on 2020-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0002_auto_20200513_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=200),
        ),
    ]
