# Generated by Django 3.0.5 on 2020-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0004_auto_20200513_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='recruit_info',
            new_name='stu_desc',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='mailbox',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='pho_num',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='stu_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='stu_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
