# Generated by Django 3.0.5 on 2020-05-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0005_auto_20200513_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('Club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubRecruitment.Club')),
            ],
        ),
    ]
