# Generated by Django 3.0.5 on 2020-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubRecruitment', '0006_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
