# Generated by Django 3.0.5 on 2020-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('pass_word', models.CharField(max_length=200)),
                ('shool', models.CharField(max_length=200)),
                ('club_name', models.CharField(max_length=200)),
                ('stu_id', models.CharField(max_length=200)),
                ('pho_num', models.CharField(max_length=200)),
            ],
        ),
    ]
